# SOIL210, hanwendong1
# https://github.com/hanwendong1/soil210
# A Jekyll template for a simple workshop website

# Site settings
# title appears in the header
title: SOIL210
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-cheese; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open; fa-coffee
title-icon: fas fa-coffee
# description and keywords for meta tags
description: "This website provides research support for students enrolled in SOIL 210 for the annotated bibliography assignment."
keywords: "soil, food, cals"
featured-image: "/images/uidaho-workshop.jpg"

# author settings for cc-by, appears in the footer
author: Hanwen Dong
Contributor: Jeremy Kenyon, Evan Will
pub_year: 2021
github_username: hanwendong1

# add the full url for the github repository
repo: "https://github.com/hanwendong1/soil210"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://hanwendong1.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /soil210

# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
# Build settings
markdown: kramdown
